import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { logoKominfo, logoKotaBatam, logoSatuData } from "./img/index";
import { ChevronDownIcon, ChevronRightIcon } from "@heroicons/react/24/solid";
import Footer from "./inc/Footer";
import Navbar from "./inc/Navbar";
import { usePathname } from "next/navigation";
import { LayoutAlt } from "./inc/LayoutAlt";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Satu Data - Portal Data Kabupaten Pelalawan",
  description: "Generated by Diskominfo Kabupaten Pelalawan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <LayoutAlt >
            {children}
          </LayoutAlt>
      </body>
    </html>
  );
}
